# Generated by Django 6.0.2 on 2026-02-22 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('business_card', 'Business Card Printing'), ('eulogy', 'Eulogy Writing & Printing'), ('general_printing', 'General Printing'), ('photocopy', 'Photocopy'), ('banner', 'Banner Printing'), ('other', 'Other Cyber Solutions')], max_length=50)),
                ('description', models.TextField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='EulogyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('eulogy_text', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='eulogies/photos/')),
                ('number_of_copies', models.PositiveIntegerField(default=1)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eulogy_document', to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCardDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_cards/logos/')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_card_design', to='core.order')),
            ],
        ),
    ]
